set(qml_import_scanner_imports_count 11)
set(qml_import_scanner_import_0 "CLASSNAME;QtQuick2Plugin;LINKTARGET;Qt6::qtquick2plugin;NAME;QtQuick;PATH;/opt/Qt/6.4.3/gcc_64/qml/QtQuick;PLUGIN;qtquick2plugin;PLUGINISOPTIONAL;;PREFER;:/qt-project.org/imports/QtQuick/;RELATIVEPATH;QtQuick;TYPE;module;")
set(qml_import_scanner_import_1 "CLASSNAME;QtQmlPlugin;LINKTARGET;Qt6::qmlplugin;NAME;QtQml;PATH;/opt/Qt/6.4.3/gcc_64/qml/QtQml;PLUGIN;qmlplugin;PLUGINISOPTIONAL;;PREFER;:/qt-project.org/imports/QtQml/;RELATIVEPATH;QtQml;TYPE;module;")
set(qml_import_scanner_import_2 "CLASSNAME;QtQmlModelsPlugin;LINKTARGET;Qt6::modelsplugin;NAME;QtQml.Models;PATH;/opt/Qt/6.4.3/gcc_64/qml/QtQml/Models;PLUGIN;modelsplugin;PLUGINISOPTIONAL;;PREFER;:/qt-project.org/imports/QtQml/Models/;RELATIVEPATH;QtQml/Models;TYPE;module;")
set(qml_import_scanner_import_3 "CLASSNAME;QtQmlWorkerScriptPlugin;LINKTARGET;Qt6::workerscriptplugin;NAME;QtQml.WorkerScript;PATH;/opt/Qt/6.4.3/gcc_64/qml/QtQml/WorkerScript;PLUGIN;workerscriptplugin;PLUGINISOPTIONAL;;PREFER;:/qt-project.org/imports/QtQml/WorkerScript/;RELATIVEPATH;QtQml/WorkerScript;TYPE;module;")
set(qml_import_scanner_import_4 "NAME;Shared;PATH;/home/saul/projects/Qt/hearth_ble/hearth/build-heartrate-game-Desktop_Qt_6_4_3_GCC_64bit-Debug/Shared;PREFER;:/;RELATIVEPATH;Shared;TYPE;module;")
set(qml_import_scanner_import_5 "NAME;.;PATH;/home/saul/projects/Qt/hearth_ble/hearth/heartrate-game/qml/GameButton.qml;TYPE;directory;")
set(qml_import_scanner_import_6 "NAME;.;PATH;/home/saul/projects/Qt/hearth_ble/hearth/heartrate-game/qml/GamePage.qml;TYPE;directory;")
set(qml_import_scanner_import_7 "CLASSNAME;QtQuick_WindowPlugin;LINKTARGET;Qt6::quickwindow;NAME;QtQuick.Window;PATH;/opt/Qt/6.4.3/gcc_64/qml/QtQuick/Window;PLUGIN;quickwindowplugin;PREFER;:/qt-project.org/imports/QtQuick/Window/;RELATIVEPATH;QtQuick/Window;TYPE;module;")
set(qml_import_scanner_import_8 "NAME;.;PATH;/home/saul/projects/Qt/hearth_ble/hearth/heartrate-game/qml/main.qml;TYPE;directory;")
set(qml_import_scanner_import_9 "NAME;.;PATH;/home/saul/projects/Qt/hearth_ble/hearth/heartrate-game/qml/SplashScreen.qml;TYPE;directory;")
set(qml_import_scanner_import_10 "NAME;.;PATH;/home/saul/projects/Qt/hearth_ble/hearth/heartrate-game/qml/StatsLabel.qml;TYPE;directory;")

